config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :items do
    resources :bookings, only: [:index, :new, :create ]
  end
    resources :bookings, only: [:show, :destroy ] do
      resources :messages, only: [:index, :new, :create]
      resources :reviews, only: [ :index, :new, :create]
    end
  get "dashboard", to: "dashboard#show"
  resources :messages, only: [:show]
  resources :reviews, only: [:show, :delete]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :item
  belongs_to :user
  has_many :messages
  has_many :reviews, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  CATEGORIES = ["Computers & Accessories", "Home & Kitchen", "Camping", "Sports & Outdoors", "Tools & DIY"]
  validates :category, inclusion: { in: CATEGORIES }
  CONDITIONS = ["Like new", "Very good", "Good", "Acceptable"]
  validates :condition, inclusion: { in: CONDITIONS }
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  has_one_attached :photo

#  geocoded_by :address, through: :users
#  after_validation :geocode, if: :will_save_change_to_address?

  def average
   if self.reviews.pluck(:rating).size.zero?
     0
   else
    ratings = 0
    self.reviews.pluck(:rating).each do |rating|
     ratings += rating
    end
    ratings / self.reviews.pluck(:rating).size
   end
  end

  def stars
    star_number = self.average.to_i
    star = "<span>&#11088;</span>"
    star * star_number
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :booking
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking

  validates :content, presence: true
  validates :rating, inclusion: { in: 0..5 }, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :authenticate_user!, :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address, :date_of_birth, :phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address, :date_of_birth, :phone_number])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  #before_action :find_booking
  def index
    @bookings = Booking.all
  end

  def show
    @booking = Booking.find(params[:id])
    @item = @booking.item
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new
    @booking.user = current_user
    @booking.item = Item.find(params[:item_id])
    if @booking.save
      redirect_to booking_path(@booking)
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to dashboard_path
  end


  private

  def booking_params
    params.require(:booking).permit(:item_id)
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def show
    @bookings = Booking.where(user: current_user)
    @booking = params[:booking_id] ? Booking.find(params[:booking_id]) : @bookings.first
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  def index
    if params[:query].present?
      @query = params[:query]
      @items = Item.where("title ILIKE ?", "%#{params[:query]}%")
      # Preventing SQL Injection and Database error for
      # unknown characters

    else
      @items = Item.all
    end
  end

  def show
    @item = Item.find(params[:id])
    # @booking = Booking.new
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user
    @item.save!
    redirect_to item_path(@item)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:title, :category, :price, :description, :condition, :delivery,
      :long_rental, :availability, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def index
    @reviews = Review.all
  end

  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to dashboard_path(booking_id: @booking.id)
    else
      render "bookings/show"
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/show.html.erb
 <!-- Load JS -->
  <%= javascript_pack_tag 'load_confirmation'%>

<div class="bg-index" id="bg-index">
  <div class="navbar navbar-expand-lg navbar-light">
    <div class="logo-and-search">
      <div class="navbar-brand">
        <%= link_to root_path do %>
        <%= image_tag "lendya-logo-yellow.png", class:"brand-logo" %>
        <% end %>
      </div>
      <div class="container-search-bar non-home-search-bar">
        <%= form_tag items_path, :class => "search-bar", method: :get do %>
          <%= text_field_tag :query,
          params[:query],
          class: "form-control search-input",
          placeholder: "Do you need anything else?"
        %>
        <%= submit_tag "Search", class: "nav-button-lender btn btn-info", id: "search-button" %>
        <% end %>
      </div>
    </div>
    <div class="d-flex justify-content-end align-items-center m-4">
      <%= link_to 'Become a lender', new_item_path, :class => "nav-button-lender btn btn-info" %>
      <% if user_signed_in? %>
      <!--<%= current_user.email %>-->
        <%= link_to 'SIGN OUT', destroy_user_session_path, method: 'delete', :class => "nav-text" %>
      <% else %>
        <%= link_to 'SIGN UP', new_user_registration_path, :class => "nav-text" %>
        <%= link_to 'LOGIN', new_user_session_path, :class => "nav-text"%>
      <% end %>
    </div>
  </div>

  <div class="under-nav-breaker">
    <!-- Make space under navbar -->
  </div>

  <div class="processing-booking" id="loading-box">
    <video class="processing-booking-video" playsinline="playsinline" autoplay="autoplay" muted="muted" loop="loop">
    <source src="<%= image_path "processing-booking-video.mp4" %>" type="video/mp4">
  </video>
  </div>

  <div class="body-container-booking" id="box">
    <div class="booking-header">
      <p>Your Booking has been confirmed!</p>
    </div>
    <div class="confirmation-container">
      <div class="booking-outline">
        <img src="<%= image_path "green-checkmark.png" %>" alt="" class="checkmark">
        <p>Your booking has been confirmed and you will receive all additional information via mail soon!</p>
        <div>
          <%= link_to 'Manage Bookings', dashboard_path(booking_id: @booking.id), :class => "btn conf-page-button" %>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/dashboard/show.html.erb
<div class="bg-show" id="bg-dash">
  <div class="navbar navbar-expand-lg navbar-light">
    <div class="logo-and-search">
      <div class="navbar-brand">
        <%= link_to root_path do %>
        <%= image_tag "lendya-logo-yellow.png", class:"brand-logo" %>
        <% end %>
      </div>
      <div class="container-search-bar non-home-search-bar" >
        <%= form_tag items_path, :class => "search-bar", method: :get do %>
          <%= text_field_tag :query,
          params[:query],
          class: "form-control search-input",
          placeholder: "Do you need anything else?"
        %>
        <%= submit_tag "Search", class: "nav-button-lender btn btn-info", id: "search-button" %>
        <% end %>
      </div>
    </div>
    <div class="d-flex justify-content-end align-items-center m-4">
      <%= link_to 'Become a lender', new_item_path, :class => "nav-button-lender btn btn-info" %>
      <% if user_signed_in? %>
      <!--<%= current_user.email %>-->
        <%= link_to 'MANAGE BOOKINGS', dashboard_path, :class => "nav-text" %>
        <%= link_to 'SIGN OUT', destroy_user_session_path, method: 'delete', :class => "nav-text" %>
      <% else %>
        <%= link_to 'SIGN UP', new_user_registration_path, :class => "nav-text" %>
        <%= link_to 'LOGIN', new_user_session_path, :class => "nav-text"%>
      <% end %>
    </div>
  </div>


  <div class="under-nav-breaker">
    <!-- Make space under navbar -->
  </div>

<div class="dashboard-header">
<p class="dash-header"><strong>Your <span class="lendya-span">lendya</span> Dashboard</strong></p>
</div>

<div class="dashboard-outline" id="dash-outline">
  <div class="bookings-column-container">
    <p class="your-bookings-header"><strong>Your Bookings:</strong></p>
    <div class="bookings-column">
    <div class="booking-column-items">
      <% @bookings.each do |booking| %>
      <%= link_to dashboard_path(booking_id: booking.id), class: "booking-link" do %>
        <div class="booking-list-item <%= "border-4 border-light" if booking == @booking %>">
          <h6><%= booking.item.title %> (<%= booking.item.category %>)</h6>
          <p>Click for Booking Information <%= booking.item.user.first_name %></p>
        </div>
      <% end %>
    <% end %>
    </div>
  </div>
  </div>
  <div class="chat-window">
    <div class="info-container">
      <div class="product-info">
        <div class="booking-img-container">
        <% if @booking.item.photo.key.nil? %>
          <img class="booking-img" src="https://images.unsplash.com/photo-1572981779307-38b8cabb2407?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332" alt="">
        <% else %>
          <%= cl_image_tag @booking.item.photo.key, class: "booking-img" %>
        <% end %>
      </div>
      </div>

      <div class="info-box">
        <h4><%= @booking.item.title %></h4>
          <div class="key-data">
            <div class="key-item"><p style="padding-left: 0px; font-size: 20px"><strong>Category:</strong> <%= @booking.item.category %>  </p></div>
            <div><p style="font-size: 20px"><strong>Condition:</strong> <%= @booking.item.condition %> </p></div>
            <div><p class="price-tag"><strong><%= @booking.item.price %> €</strong> / Day</div>
          </div>
        <h6><strong>Description:</strong></h6>
        <div class="dashboard-description">
          <% if !@booking.item.description.empty? %>
          <p><%= @booking.item.description %></p>
        <% else %>
          <p>The owner hasn't provided a desciption yet</p>
        <% end %>
        </div>
        <div class="item-extras">
          <div class="list-item extra-item">
            <% if @booking.item.long_rental == true %>
              <p style="font-size: 20px">&#10004;	Owner accepts long rental</p>
            <% else %>
              <p style="font-size: 20px">&#10060; Owner doesn't accept long rental</p>
            <% end %>
          </div>
          <div class="list-item extra-item">
            <% if @booking.item.delivery == true %>
              <p style="font-size: 20px">	&#10004; Owner offers to deliver</p>
            <% else %>
              <p style="font-size: 20px">&#10060; Owner doesn't deliver</p>
            <% end %>
          </div>
        </div>
        <div class="button-group align-items-center">
          <div> <%= link_to 'Check Item', item_path(@booking.item), :class => "nav-button-lender btn btn-info sized dash-buttons left-button" %>
          </div>
          <div> <%= link_to 'Rate Booking', new_booking_review_path(@booking), :class => "nav-button-lender btn btn-info sized dash-buttons" %>
          </div>
          <div> <%= link_to 'Cancel Booking', booking_path(@booking), method: :delete, :class => "nav-button-lender btn btn-info sized dash-buttons" %>
          </div>
        </div>
      </div>
    </div>

  </div>

    <%#<div class="button-group justify-content-center align-items-center m-4">
      <div> <%= link_to 'Find more Items', items_path, :class => "nav-button-lender btn btn-info sized" %>
      <%#</div>
      <div> <%= link_to 'Return to Home', root_path, :class => "nav-button-lender btn btn-info sized" %>
      <%#</div>
    <%#</div> %>

  </div>
</div>

</div>

app/views/items/index.html.erb
<!-- Load JS -->
<%= javascript_pack_tag 'button_scroller', defer: true %>

<div class="bg-index" id="bg-index">
  <div class="navbar navbar-expand-lg navbar-light">
    <div class="logo-and-search">
      <div class="navbar-brand">
        <%= link_to root_path do %>
        <%= image_tag "lendya-logo-yellow.png", class:"brand-logo" %>
        <% end %>
      </div>
      <div class="container-search-bar non-home-search-bar">
        <%= form_tag items_path, :class => "search-bar", method: :get do %>
          <%= text_field_tag :query,
          params[:query],
          class: "form-control search-input",
          placeholder: "Do you need anything else?"
        %>
        <%= submit_tag "Search", class: "nav-button-lender btn btn-info", id: "search-button" %>
        <% end %>
      </div>
    </div>
    <div class="d-flex justify-content-end align-items-center m-4">
      <%= link_to 'Become a lender', new_item_path, :class => "nav-button-lender btn btn-info" %>
      <% if user_signed_in? %>
      <!--<%= current_user.email %>-->
        <%= link_to 'MANAGE BOOKINGS', dashboard_path, :class => "nav-text" %>
        <%= link_to 'SIGN OUT', destroy_user_session_path, method: 'delete', :class => "nav-text" %>
      <% else %>
        <%= link_to 'SIGN UP', new_user_registration_path, :class => "nav-text" %>
        <%= link_to 'LOGIN', new_user_session_path, :class => "nav-text"%>
      <% end %>
    </div>
  </div>

  <div class="under-nav-breaker">
    <!-- Make space under navbar -->
  </div>


  <div class="container-number-items">
    <div class="text-center p-2">
      <div class="col">
        <% if @query %>
          <p>You searched for <strong><%= @query %></strong>. We found <%= @items.count %> items out of our <%= Item.count %> on our website.</p>
        <% else %>
          <p>All <%= Item.count %> items</p>
        <% end %>
      </div>
    </div>
  </div>

  <div class="cards" id="cards-container">
    <% @items.each do |item| %>
      <div class="item-card">
        <%= link_to  item_path(item) do %>
        <div class="item-card-image">
          <% if item.photo.key.nil? %>
          <% else %>
            <%= cl_image_tag item.photo.key, class: "item-avatar" %>
          <% end %>
        </div>
        <div class="card-item-content">
          <h2><%= item.title %></h2>
          <p><%= item.category %></p>
        </div>
        <div class="card-item-pricing">
          <div class="rate">
          <%= sanitize item.stars %>
          <span>(<%= item.average.round(1) %>)</span>
          <% if item.reviews.length < 1 %>
          <small><p><%= "No reviews"%></p></small>
          <% elsif item.reviews.length == 1 %>
            <small><p><%= "#{item.reviews.length} review"%></p></small>
          <% else  %>
            <small><p><%= "#{item.reviews.length} reviews"%></p></small>
          <% end %>
          </div>
          <h2><%= item.price %> € / Day</h2>
        </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <h3 class="text-center"><%= link_to "Go back", root_path, :class => "btn btn-link" %></h3>

<button type="button" class="btn btn-info btn-floating btn-lg" id="btn-back-to-top">
  <i class="fas fa-arrow-up" style="color: white;"></i>
</button>

</div>

<!-- Load JS -->
<%= javascript_pack_tag 'adjust_bg_index' %>

app/views/items/new.html.erb
<div class="navbar navbar-expand-lg navbar-light">
  <div class="navbar-brand">
    <img src="<%= image_path "lendya-logo-yellow.png" %>" alt="Lendya Logo" class="brand-logo">
  </div>
  <div class="d-flex justify-content-end align-items-center m-4">
    <%= link_to 'Become a lender', new_item_path, :class => "nav-button-lender btn btn-info" %>
    <% if user_signed_in? %>
    <!--<%= current_user.email %>-->
      <%= link_to 'SIGN OUT', destroy_user_session_path, method: 'delete', :class => "nav-text" %>
    <% else %>
      <%= link_to 'SIGN UP', new_user_registration_path, :class => "nav-text" %>
      <%= link_to 'LOGIN', new_user_session_path, :class => "nav-text"%>
    <% end %>
  </div>
</div>



<div class="container py-5">
  <div class="row">
    <div class="form-upload shadow-sm p-3 mb-5 bordered col-12 col-md-6 offset-lg-3 justify-content-center p-5">
      <div class="shadow-md rounded px-8 pt-6 pb-8 mb-4">
          <div class="centered"> <h2>Share your item with the community!</h2></div>
            <%= simple_form_for(@item) do |f| %>
              <%= f.input :title, placeholder: "Name your item", class: "form-inputs" %>
              <%= f.input :category, collection: Item::CATEGORIES, placeholder: "What's the category?", :class => "input-field" %>
              <%= f.input :price, placeholder: "What's the daily price?", :class => "input-field" %>
              <%= f.input :description, placeholder: "Provide some more info!", :class => "input-field" %>
              <%= f.input :condition, collection: Item::CONDITIONS, placeholder: "How would you describe the condition?", :class => "input-field" %>
              <%= f.input :delivery, placeholder: "Can you deliver the item?", :class => "input-field" %>
              <%= f.input :long_rental, :class => "input-field" %>
              <%= f.input :availability, :class => "input-field" %>
              <%= f.input :photo, as: :file, :class => "input-field" %>

              <div>
                <p class="text-center text-gray-500 text-xs">
                Make sure that all information is correct!
                </p>
              </div>
              <div class="text-center">
                <%= f.button :submit, "Upload", class: "btn btn-warning upload-btn nav-text" %>
              </div>
          </div>
            <div class="centered">
              <%= link_to 'Back', items_path %>
            </div>

      </div>
      </div>
  </div>


            <% end %>

app/views/items/show.html.erb
<!-- Load JS -->
<%= javascript_pack_tag 'calc_days', defer: true %>
<%= javascript_pack_tag 'button_scroller', defer: true %>


<div class="bg-show" id=bg-show>
  <div class="navbar navbar-expand-lg navbar-light">
    <div class="logo-and-search">
      <div class="navbar-brand">
        <%= link_to root_path do %>
        <%= image_tag "lendya-logo-yellow.png", class:"brand-logo" %>
        <% end %>
      </div>
      <div class="container-search-bar non-home-search-bar" >
        <%= form_tag items_path, :class => "search-bar", method: :get do %>
          <%= text_field_tag :query,
          params[:query],
          class: "form-control search-input",
          placeholder: "Do you need anything else?"
        %>
        <%= submit_tag "Search", class: "nav-button-lender btn btn-info", id: "search-button" %>
        <% end %>
      </div>
    </div>
    <div class="d-flex justify-content-end align-items-center m-4">
      <%= link_to 'Become a lender', new_item_path, :class => "nav-button-lender btn btn-info" %>
      <% if user_signed_in? %>
      <!--<%= current_user.email %>-->
        <%= link_to 'MANAGE BOOKINGS', dashboard_path, :class => "nav-text" %>
        <%= link_to 'SIGN OUT', destroy_user_session_path, method: 'delete', :class => "nav-text" %>
      <% else %>
        <%= link_to 'SIGN UP', new_user_registration_path, :class => "nav-text" %>
        <%= link_to 'LOGIN', new_user_session_path, :class => "nav-text"%>
      <% end %>
    </div>
  </div>

  <div class="show-container" id="show-container">
    <div class="item-show-container">
      <div class="item-show-header">
        <h4><%= @item.title %> <span><%= link_to 'Take offer down', @item, :class => "btn btn-secondary btn-sm take-down", method: :delete, data: { confirm: 'Are you sure?' } %></span></h4>
        <div class="item-header-info">
          <div class="rate">
            <span>
            <%= sanitize @item.stars %>
            (<%= @item.average.round(1) %>) &#183;
            <% if @item.reviews.length < 1 %>
              <%= "No reviews"%>
            <% elsif @item.reviews.length == 1 %>
              <%= "#{@item.reviews.length} review"%>
            <% else  %>
              <%= "#{@item.reviews.length} reviews"%>
            <% end %>
            </span>
          </div>
            <% if @item.availability == true %>
            <p class="available-text">The <strong><%= @item.title %></strong> is availabe! Go rent it!</p>
            <% else %>
            <p class="not-available-text">The <strong><%= @item.title %></strong> is currently not available!</p>
            <% end %>
        </div>
        <% if @item.photo.key.nil? %>
          <img src="https://images.unsplash.com/photo-1572981779307-38b8cabb2407?crop=entropy&cs=tinysrgb&fm=jpg&ixlib=rb-1.2.1&q=80&raw_url=true&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332" alt="">
        <% else %>
          <%= cl_image_tag @item.photo.key, class: "item-img" %>
        <% end %>
      </div>
      <div class="item-extras">
        <div class="list-item extra-item">
          <% if @item.long_rental == true %>
            <p>&#10004;	Owner accepts long rental</p>
          <% else %>
            <p>&#10060; Owner doesn't accept long rental</p>
          <% end %>
        </div>
        <div class="list-item extra-item">
          <% if @item.delivery == true %>
            <p>&#10004;	Owner offers to deliver</p>
          <% else %>
            <p>&#10060; Owner doesn't deliver</p>
          <% end %>
        </div>
      </div>
      <h6 class="show-headers"><strong>Description:</strong></h6>
      <div class="item-description">
        <% if !@item.description.empty? %>
          <p><%= @item.description %></p>
        <% else %>
          <p>The owner hasn't provided a desciption yet</p>
        <% end %>
      </div>
      <h6 class="show-headers"><strong>Reviews:</strong></h6>
      <div class="reviews">
        <div class="list-group">
          <% @item.reviews.each do |review| %>
          <li class="list-group-item review-content">
            <small>
              <% count = 0 %>
              <% 5.times do %>
                <% if review.rating > count %>
                  <span>&#11088;</span>
                <% else %>
                  <i class="far fa-star empty-stars"></i>
                <% end %>
                <% count += 1 %>
              <% end %>
            </small>
            <p><%= review.content %></p>
          </li>
        <% end %>
      </div>
      </div>
    </div>
    <div class="middle-breaker-container"></div>
    <div class="booking-confirm-outer-container">
      <div class="booking-confirm-inner-container">
        <div class="item-show-price">
          <p class="checkout-header">Checkout</p>
        </div>
          <% days_booked = 0 %>
          <%= simple_form_for :booking do |f| %>
          <%= f.error_notification %>
          <div class="rental-inputs">
            <div class="wrapper-input">
              <%= f.input :pick_up, as: :date, start_year: Date.today.year, end_year: Date.today.year, discard_year: true, order:[:day, :month], input_html: { class: "date-inputs"}, label_html: { class: "date-label", id: "pick-up-day"}, required: false %>
            </div>
            <div class="wrapper-input">
              <%= f.input :return, as: :date, start_year: Date.today.year, end_year: Date.today.year, discard_year: true, order:[:day, :month], input_html: { class: "date-inputs"}, label_html: { class: "date-label", id: "return-days"}, required: false%>
            </div>
          </div>
          <% end %>
        <div class="booking-button">
          <%= link_to "Confirm Booking", item_bookings_path(@item), method: :post, :class => "btn"%>
        </div>
        <div class="price-calculation-days row">
          <div class="col-sm">
          <p class="price-title"><span id="item-price"><%= @item.price %></span> € x <span id="days"> 1 </span> days</p>
          </div>
          <div class="col-sm">
            <p class="price-number"><span id="item-price-between"> <%= @item.price %></span> €</p>
          </div>
        </div>
        <div class="price-service-fee row">
          <div class="col-sm">
          <p class="price-title">Service fee</p>
          </div>
          <div class="col-sm">
            <p class="price-number">3 €</p>
          </div>
        </div>
        <div class="price-calculation-total row">
          <div class="col-sm">
            <p class="price-total"><strong>Total</strong></p>
          </div>
          <div class="col-sm">
            <p class="price-number"><strong><span id="item-price-total"> <%= @item.price + 3 %></span> €</strong></p>
          </div>
        </div>
        </div>
      </div>
    </div>
  </div>
  <button type="button" class="btn btn-info btn-floating btn-lg" id="btn-back-to-top">
  <i class="fas fa-arrow-up" style="color: white;"></i>
  </button>
</div>

<!-- Load JS -->
<%= javascript_pack_tag 'adjust_bg_show' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lendya</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
<!--
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
!-->

    <%= yield %>
  </body>
</html>

app/views/layouts/index.html.erb
<%= link_to 'Edit Profile', edit_user_registration_path %>
<%#= 12345added new file: Step 7 on https://gist.github.com/withoutwax/46a05861aa4750384df971b641170407 %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-lg navbar-light">
  <div class="navbar-brand">
    <img src="<%= image_path "lendya-logo1.png" %>" alt="Lendya Logo" class="brand-logo">
  </div>
  <div class="d-flex justify-content-end align-items-center m-4">
    <%= link_to 'Become a lender', new_item_path, :class => "nav-button-lender btn btn-warning" %>
    <% if user_signed_in? %>
    <!--<%= current_user.email %>-->
      <%= link_to 'SIGN OUT', destroy_user_session_path, method: 'delete', :class => "nav-text" %>
    <% else %>
      <%= link_to 'SIGN UP', new_user_registration_path, :class => "nav-text" %>
      <%= link_to 'LOGIN', new_user_session_path, :class => "nav-text"%>
    <% end %>
  </div>
</div>